### ISSUE TITLE
Review commands

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#70]
.rev, .revtell, .revs, .revafk , .revedit and .revto .
Also the clean buffer correspondences (.cbuff, .ctells, etc.)

**Comment by marado** [comment]
It would be nice to also be able to throw in a number of lines argument (eg.: .rev 5 shows the last five lines)

**Comment by marado** [comment]
Step by step:
* [ ] .rev
* [ ] .cbuff
* [ ] .revlengthdefault
* [ ] .revlength
* [ ] .revtell
* [ ] .revs
* [ ] .revafk - pending on #93 
* [ ] .revedit - pending on #52
* [ ] .revto - pending on #85
